config/routes.rb
Rails.application.routes.draw do
  root                'static_pages#home'
  get    'help'    => 'static_pages#help'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get    'resend_activation'  =>  'account_activations#new_resend_activation'
  post   'resend_activation'  =>  'account_activations#resend_activation',
                                        :constraints => { :email => /[^\/]+/ }
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :listings
  resources :listing_attachments, only: [:destroy]
  resources :searches

end

app/models/listing.rb
class Listing < ActiveRecord::Base
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  has_many :listing_attachments, dependent: :destroy
  accepts_nested_attributes_for :listing_attachments
  validates :user_id, presence: true

  def title
  	self.name + ' ' +  self.brand + ' (' + self.year.to_s + ')'
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :logged_in_user, only: [:new, :create, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update, :destroy]

  def show
    @listing = Listing.find(params[:id])
    @listing_attachments = @listing.listing_attachments.all
  end

  def new
  	@listing = Listing.new
  	@listing_attachment = @listing.listing_attachments.build
  end

  def edit
    # @listing = Listing.find(params[:id])
    @listing_attachment = @listing.listing_attachments.build
    @listing_pic_attachments = @listing.listing_attachments.where(attachment_group: 'picture')
  end

  def destroy
    @listing.destroy
    flash[:success] = "Listing successfully deleted."
    # redirect_to request.referrer || root_url
    redirect_to current_user
  end

  def create
    @listing = current_user.listings.build(listing_params)
    if @listing.save
      unless params[:listing_pic_attachments].nil?
        params[:listing_pic_attachments]['image'].each do |a|
            @listing_attachment = @listing.listing_attachments.create!(image: a, attachment_group: 'picture')
        end
      end
      flash[:success] = "Listing successfully created."
      redirect_to @listing
    else
      render 'new'
    end
  end

  def update
    # @listing = Listing.find(params[:id])
    if @listing.update_attributes(listing_params)
      flash[:success] = "Listing successfully updated."
      redirect_to @listing
    else
      render 'edit'
    end
  end

  def search
  end

  private

    def listing_params
      params.require(:listing).permit(:name, :brand, :modeltype, :origin, :hourmeter, :year, :price, :condition, :sell_status, :lease_status, :location, :description,
                                        post_attachments_attributes: [:id, :listing_id, :image, :attachment_group])
    end

    def correct_user
      @listing = current_user.listings.find_by(id: params[:id])
      redirect_to root_url if @listing.nil?
    end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<%= form_for(@listing) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div id="step1" class="form-group row">
    <div class="col-sm-3 form-label">
      <%= f.label :name, 'Jenis alat' %>
    </div>
    <div class="col-sm-9">
      <!-- <%= f.text_field :name, class: 'form-control' %> -->
      <%= f.radio_button :name, 'Excavator', class: 'grey-btn' %>
      <%= f.label :name, 'Excavator', value: 'Excavator' %>
      <%= f.radio_button :name, 'Bulldozer', class: 'grey-btn' %>
      <%= f.label :name, 'Bulldozer', value: 'Bulldozer' %>
      <%= f.radio_button :name, 'Motor Grader', class: 'grey-btn' %>
      <%= f.label :name, 'Motor Grader', value: 'Motor Grader' %>
      <%= f.radio_button :name, 'Wheel Loader', class: 'grey-btn' %>
      <%= f.label :name, 'Wheel Loader', value: 'Wheel Loader' %>
      <%= f.radio_button :name, 'Backhoe Loader', class: 'grey-btn' %>
      <%= f.label :name, 'Backhoe Loader', value: 'Backhoe Loader' %>
      <%= f.radio_button :name, 'Tractor', class: 'grey-btn' %>
      <%= f.label :name, 'Tractor', value: 'Tractor' %>
      <%= f.radio_button :name, 'Compactor/Roller', class: 'grey-btn' %>
      <%= f.label :name, 'Compactor/Roller', value: 'Compactor/Roller' %>
      <%= f.radio_button :name, 'Forklift', class: 'grey-btn' %>
      <%= f.label :name, 'Forklift', value: 'Forklift' %>
      <%= f.radio_button :name, 'Crane', class: 'grey-btn' %>
      <%= f.label :name, 'Crane', value: 'Crane' %>
      <%= f.radio_button :name, 'Asphalt Finisher', class: 'grey-btn' %>
      <%= f.label :name, 'Asphalt Finisher', value: 'Asphalt Finisher' %>
    </div>
  </div>
  <div id="step2" class="form-group row">
    <div class="col-sm-3 form-label">
      <%= f.label :brand, 'Jenis merk' %>
    </div>
    <div class="col-sm-9">
      <!-- <%= f.text_field :brand, class: 'form-control' %> -->
      <%= f.radio_button :brand, 'Bobcat', class: 'grey-btn' %>
      <%= f.label :brand, 'Bobcat', value: 'Bobcat' %>
      <%= f.radio_button :brand, 'Bomag', class: 'grey-btn' %>
      <%= f.label :brand, 'Bomag', value: 'Bomag' %>
      <%= f.radio_button :brand, 'Case', class: 'grey-btn' %>
      <%= f.label :brand, 'Case', value: 'Case' %>
      <%= f.radio_button :brand, 'Caterpillar', class: 'grey-btn' %>
      <%= f.label :brand, 'Caterpillar', value: 'Caterpillar' %>
      <%= f.radio_button :brand, 'Hitachi', class: 'grey-btn' %>
      <%= f.label :brand, 'Hitachi', value: 'Hitachi' %>
      <%= f.radio_button :brand, 'Hyundai', class: 'grey-btn' %>
      <%= f.label :brand, 'Hyundai', value: 'Hyundai' %>
      <%= f.radio_button :brand, 'JCB', class: 'grey-btn' %>
      <%= f.label :brand, 'JCB', value: 'JCB' %>
      <%= f.radio_button :brand, 'John Deere', class: 'grey-btn' %>
      <%= f.label :brand, 'John Deere', value: 'John Deere' %>
      <%= f.radio_button :brand, 'Kato', class: 'grey-btn' %>
      <%= f.label :brand, 'Kato', value: 'Kato' %>
      <%= f.radio_button :brand, 'Keihatsu', class: 'grey-btn' %>
      <%= f.label :brand, 'Keihatsu', value: 'Keihatsu' %>
      <%= f.radio_button :brand, 'Kobelco', class: 'grey-btn' %>
      <%= f.label :brand, 'Kobelco', value: 'Kobelco' %>
      <%= f.radio_button :brand, 'Komatsu', class: 'grey-btn' %>
      <%= f.label :brand, 'Komatsu', value: 'Komatsu' %>
      <%= f.radio_button :brand, 'Kubota', class: 'grey-btn' %>
      <%= f.label :brand, 'Kubota', value: 'Kubota' %>
      <%= f.radio_button :brand, 'Liu Gong', class: 'grey-btn' %>
      <%= f.label :brand, 'Liu Gong', value: 'Liu Gong' %>
      <%= f.radio_button :brand, 'Lonking', class: 'grey-btn' %>
      <%= f.label :brand, 'Lonking', value: 'Lonking' %>
      <%= f.radio_button :brand, 'Massey Ferguson', class: 'grey-btn' %>
      <%= f.label :brand, 'Massey Ferguson', value: 'Massey Ferguson' %>
      <%= f.radio_button :brand, 'Mitsubishi', class: 'grey-btn' %>
      <%= f.label :brand, 'Mitsubishi', value: 'Mitsubishi' %>
      <%= f.radio_button :brand, 'New Holland', class: 'grey-btn' %>
      <%= f.label :brand, 'New Holland', value: 'New Holland' %>
      <%= f.radio_button :brand, 'Sakai', class: 'grey-btn' %>
      <%= f.label :brand, 'Sakai', value: 'Sakai' %>
      <%= f.radio_button :brand, 'Sany', class: 'grey-btn' %>
      <%= f.label :brand, 'Sany', value: 'Sany' %>
      <%= f.radio_button :brand, 'Shantui', class: 'grey-btn' %>
      <%= f.label :brand, 'Shantui', value: 'Shantui' %>
      <%= f.radio_button :brand, 'Sumitomo', class: 'grey-btn' %>
      <%= f.label :brand, 'Sumitomo', value: 'Sumitomo' %>
      <%= f.radio_button :brand, 'Tadano', class: 'grey-btn' %>
      <%= f.label :brand, 'Tadano', value: 'Tadano' %>
      <%= f.radio_button :brand, 'Takeuchi', class: 'grey-btn' %>
      <%= f.label :brand, 'Takeuchi', value: 'Takeuchi' %>
      <%= f.radio_button :brand, 'Terex', class: 'grey-btn' %>
      <%= f.label :brand, 'Terex', value: 'Terex' %>
      <%= f.radio_button :brand, 'Toyota', class: 'grey-btn' %>
      <%= f.label :brand, 'Toyota', value: 'Toyota' %>
      <%= f.radio_button :brand, 'Volvo', class: 'grey-btn' %>
      <%= f.label :brand, 'Volvo', value: 'Volvo' %>
      <%= f.radio_button :brand, 'XCMG', class: 'grey-btn' %>
      <%= f.label :brand, 'XCMG', value: 'XCMG' %>
    </div>
  </div>
  <div id="step3">
    <div class="form-group row">
      <div class="col-sm-3 form-label">
      <%= f.label :modeltype, 'Jenis tipe' %>
      </div>
      <div class="col-sm-9">
      <%= f.text_field :modeltype, placeholder: 'Isi tipe', class: 'form-control' %>
      </div>
    </div>
    <div class="form-group row">
      <div class="col-sm-3 form-label">
      <%= f.label :origin, 'Asal alat' %>
      </div>
      <div class="col-sm-9">
      <%= f.radio_button :origin, 'Lokal', class: 'grey-btn' %>
      <%= f.label :origin, 'Lokal', value: 'Lokal' %>
      <%= f.radio_button :origin, 'Import', class: 'grey-btn' %>
      <%= f.label :origin, 'Import', value: 'Import' %>
      </div>
    </div>
    <div class="form-group row">
      <div class="col-sm-3 form-label">
      <%= f.label :hourmeter, 'Hour meter' %>
      </div>
      <div class="col-sm-9">
      <%= f.text_field :hourmeter, placeholder: 'Isi hour meter', class: 'form-control' %>
      </div>
    </div>
    <div class="form-group row">
      <div class="col-sm-3 form-label">
      <%= f.label :year, 'Tahun alat' %>
      </div>
      <div class="col-sm-9">
      <%= f.text_field :year, placeholder: 'Isi tahun', class: 'form-control' %>
      </div>
    </div>
    <div class="form-group row">
      <div class="col-sm-3 form-label">
      <%= f.label :price, 'Harga' %>
      </div>
      <div class="col-sm-9">
      <%= f.text_field :price, placeholder: 'Isi harga (Rupiah)', data: {autonumeric: {aSign: 'Rp ', mDec: 0, aDec: ',', aSep: '.'}}, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group row">
      <div class="col-sm-3 form-label">
      <%= f.label :condition, 'Kondisi alat' %>
      </div>
      <div class="col-sm-9">
      <%= f.radio_button :condition, 'Baru', class: 'grey-btn' %>
      <%= f.label :condition, 'Baru', value: 'Baru' %>
      <%= f.radio_button :condition, 'Bekas', class: 'grey-btn' %>
      <%= f.label :condition, 'Bekas', value: 'Bekas' %>
      </div>
    </div>
    <div class="form-group row">
      <div class="col-sm-3 form-label">
      <%= f.label :sell_status, 'Status alat' %>
      </div>
      <div class="col-sm-9">
      <%= f.check_box :sell_status, class: 'grey-btn' %>
      <%= f.label :sell_status, 'Dijual' %>
      <%= f.check_box :lease_status, class: 'grey-btn' %>
      <%= f.label :lease_status, 'Disewakan' %>
      </div>
    </div>
    <div class="form-group row">
      <div class="col-sm-3 form-label">
      <%= f.label :location, 'Lokasi' %>
      </div>
      <div class="col-sm-9">
      <%= f.text_field :location, placeholder: 'Isi lokasi', class: 'form-control' %>
      </div>
    </div>
    <div class="form-group row">
      <div class="col-sm-3 form-label">
      <%= f.label :description, 'Deskripsi' %>
      </div>
      <div class="col-sm-9">
      <%= f.text_area :description, placeholder: 'Isi deskripsi', class: 'form-control' %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.fields_for :listing_attachment do |p| %>
        <div class="col-sm-3 form-label">
          <%= p.label :image %><br>
        </div>
        <div class="col-sm-9">
          <%= p.file_field :image, :multiple => true, name: "listing_pic_attachments[image][]", accept: 'image/jpeg,image/gif,image/png', class: 'form-control-file' %>
        </div>
      <% end %>
    </div>
    <%= f.submit yield(:button_text), class: "btn btn-primary" %>
  </div>
<% end %>

<script type="text/javascript">
  $('#listing_attachment_image').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/listings/_listing.html.erb
<li id="listing-<%= listing.id %>">
  <%= link_to gravatar_for(listing.user, size: 50), listing.user %>
  <span class="name"><%= link_to listing.name, listing %></span>
  <span class="hourmeter">Hour Meter : <%= listing.hourmeter %></span>
  <span class="status">Status : <%= 'dijual' if listing.sell_status %><%= ', ' if listing.sell_status && listing.lease_status %><%= 'disewakan' if listing.lease_status %></span>
  <span class="location">Lokasi : <%= listing.location %></span>
  <span class="user">Penjual : <%= link_to listing.user.name, listing.user %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(listing.created_at) %> ago.
  </span>    
  <% if current_user?(listing.user) %>
    <%= link_to "delete", listing, method: :delete, data: { confirm: "Are you sure?" } %>
  <% end %>
</li>

app/views/listings/edit.html.erb
<% provide(:title, "Edit listing") %>
<% provide(:button_text, 'Save changes') %>
<h1>Edit Listing</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
    <div>
    <table>
  <thead>
    <tr>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @listing_pic_attachments.each do |listing_attachment| %>
      <tr>
        <td><%= listing_attachment.image %></td>
        <td><%= link_to 'Delete', listing_attachment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
  </table>
    </div>
  </div>
</div>

app/views/listings/new.html.erb
<% provide(:title, 'Create New Listing') %>
<% provide(:button_text, 'Submit') %>
<h1>Create New Listing</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/listings/show.html.erb
<% provide(:title, @listing.name) %>
<div class="row">
  <div class="col-xs-12">
    <h1 class="listing-headline">
      <%= link_to @listing.title, @listing %>
    </h1>
    <div id="slider" class="flexslider">
      <ul class="slides">
        <% @listing_attachments.each do |l| %>
          <li>
            <%= image_tag l.image_url %>
          </li>
        <% end %>
      </ul>
    </div>
    <div>
      <span class="current-slide"></span>
      <span>/</span>
      <span class="total-slides"></span>
    </div>
    <div id="carousel" class="flexslider">
      <ul class="slides">
        <% @listing_attachments.each do |l| %>
          <li>
            <%= image_tag l.image_url %>
          </li>
        <% end %>
      </ul>
    </div>
    <div class="row">
      <div class="col-md-8">
        <h2 class="listing-subhead">
          Data Spesifikasi
        </h2>
        <div class="listing-box">
          <div class="row">
            <div class="col-xs-3"><span>Merk</span></div>
            <div class="col-xs-1"><span>:</span></div>
            <div class="col-xs-8"><span><%= @listing.brand %></span></div>
          </div>
          <div class="row">
            <div class="col-xs-3"><span>Nama</span></div>
            <div class="col-xs-1"><span>:</span></div>
            <div class="col-xs-8"><span><%= @listing.name %></span></div>
          </div>
          <div class="row">
            <div class="col-xs-3"><span>Tipe</span></div>
            <div class="col-xs-1"><span>:</span></div>
            <div class="col-xs-8"><span><%= @listing.modeltype %></span></div>
          </div>
          <div class="row">
            <div class="col-xs-3"><span>Tahun</span></div>
            <div class="col-xs-1"><span>:</span></div>
            <div class="col-xs-8"><span><%= @listing.year %></span></div>
          </div>
          <div class="row">
            <div class="col-xs-3"><span>Hour meter</span></div>
            <div class="col-xs-1"><span>:</span></div>
            <div class="col-xs-8"><span><%= @listing.hourmeter %> jam kerja</span></div>
          </div>
          <div class="row">
            <div class="col-xs-3"><span>Asal</span></div>
            <div class="col-xs-1"><span>:</span></div>
            <div class="col-xs-8"><span><%= @listing.origin %></span></div>
          </div>
          <div class="row">
            <div class="col-xs-3"><span>Kondisi</span></div>
            <div class="col-xs-1"><span>:</span></div>
            <div class="col-xs-8"><span><%= @listing.condition %></span></div>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div>
          <h2 class="listing-subhead">
            Harga
          </h2>
          <div class="listing-box">
            <div class="row">
              <div class="col-xs-12">
                <span class="price-tag"><%= number_to_currency @listing.price, locale: :id, precision: 0, format: "%u %n" %></span>
              </div>
            </div>
          </div>
        </div>
        <div>
          <h2 class="listing-subhead">
            Dokumen Dukungan
          </h2>
          <div class="listing-box">
          </div>
        </div>
        <div>
          <h2 class="listing-subhead">
            Status
          </h2>
          <div class="listing-box">
            <div class="row">
              <div class="col-xs-6">
                <div class="<%= @listing.sell_status ? 'tick' : 'cross' %>">
                </div>
                <span>
                  Untuk Dijual
                </span>
              </div>
              <div class="col-xs-6">
                <div class="<%= @listing.lease_status ? 'tick' : 'cross' %>">
                </div>
                <span>
                  Untuk Disewakan
                </span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-md-8">
        <h2 class="listing-subhead">
          Deskripsi
        </h2>
        <div class="listing-box">
          <span>
            <%= @listing.description %>
          </span>
        </div>
      </div>
      <div class="col-md-4">
        <div>
          <h2 class="listing-subhead">
            Lokasi
          </h2>
          <div class="listing-box">
            <span>
              <%= @listing.location %>
            </span>
          </div>
        </div>
        <div>
          <h2 class="listing-subhead">
            Informasi Penjual
          </h2>
          <div class="listing-box">
            <span>
              <%= link_to @listing.user.name, @listing.user %>
            </span>
          </div>
        </div>
      </div>
    </div>

    <section class="listing_control">
    <% if current_user?(@listing.user) %>
      <%= link_to "Delete Listing", @listing, method: :delete, data: { confirm: "Are you sure?" } %><br>
      <%= link_to "Edit Listing", edit_listing_path(@listing) %>
    <% end %>
    </section>
  </div>
</div>