config/routes.rb
Rails.application.routes.draw do
  root                'static_pages#home'
  get    'help'    => 'static_pages#help'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get    'resend_activation'  =>  'account_activations#new_resend_activation'
  post   'resend_activation'  =>  'account_activations#resend_activation',
                                        :constraints => { :email => /[^\/]+/ }
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :listings
  resources :listing_attachments, only: [:destroy]
  resources :searches

end

app/controllers/account_activations_controller.rb
class AccountActivationsController < ApplicationController

  def edit
    user = User.find_by(email: params[:email])
    if user && !user.activated? && user.authenticated?(:activation, params[:id])
      user.activate
      log_in user
      flash[:success] = "Account successfully activated!"
      redirect_to user
    else
      flash[:danger] = "Invalid activation link"
      redirect_to root_url
    end
  end

  def new_resend_activation
  end

  def resend_activation
    user = User.find_by(email: params[:resend_activation][:email])
    if user
      user.resend_activation_email
      flash[:info] = "Please check your email to activate your account."
      redirect_to login_url
    else
      flash[:danger] = "There was no account found for your e-mail address."
      redirect_to resend_activation_url
    end
  end

end

app/helpers/account_activations_helper.rb
module AccountActivationsHelper
end

app/views/account_activations/new_resend_activation.html.erb
<% provide(:title, "Resend activation link") %>
<h1>Resend activation link</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:resend_activation, url: resend_activation_path) do |f| %>
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.submit "Submit", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>