config/routes.rb
Rails.application.routes.draw do
  root                'static_pages#home'
  get    'help'    => 'static_pages#help'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get    'resend_activation'  =>  'account_activations#new_resend_activation'
  post   'resend_activation'  =>  'account_activations#resend_activation',
                                        :constraints => { :email => /[^\/]+/ }
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :listings
  resources :listing_attachments, only: [:destroy]
  resources :searches

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <small>
      © 2016 Utiliti
    </small>
    <nav>
      <ul>
        <li><%= link_to "About",   about_path %></li>
        <li><%= link_to "Contact", contact_path %></li>
      </ul>
    </nav>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top custom-navbar" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbarCollapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "", root_path, id: "logo" %>
    </div>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="nav navbar-nav navbar-utiliti">
        <li><%= link_to "Tentang Utiliti",   about_path %></li>
        <li><%= link_to "Cari Alat",   new_search_path %></li>
        <li><%= link_to "Lihat Alat",   help_path %></li>
        <li><%= link_to "Jual Alat", new_listing_path %></li>
        <li><%= link_to "Hubungi Kami", contact_path %></li>
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Daftar - Masuk", login_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>

  <!-- flexslider -->
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script type="text/javascript" charset="utf-8">
    $(document).on("turbolinks:load", function() {
      // The slider being synced must be initialized first
      $('#carousel').flexslider({
        animation: "slide",
        controlNav: false,
        animationLoop: false,
        slideshow: false,
        itemWidth: 210,
        itemMargin: 5,
        asNavFor: '#slider'
      });
     
      $('#slider').flexslider({
        animation: "slide",
        controlNav: false,
        animationLoop: true,
        slideshow: false,
        sync: "#carousel",
        start: function(slider) {
          $('.current-slide').text(slider.currentSlide+1);
          $('.total-slides').text(slider.count);
        },
        after: function(slider) {
          $('.current-slide').text(slider.currentSlide+1);
        }
      });

      $(document).trigger('refresh_autonumeric');
    });
  </script>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= sanitize(message) %></div>
    <% end %>
    <%= yield %>
    <%= debug(params) if Rails.env.development? %>
  </div>
  <%= render 'layouts/footer' %>
</body>
</html>